### ISSUE TITLE
Reloads lose namespaces

### ISSUE THREAD

**Issue by sdegutis** [slagyr/speclj#109] opened 2014-09-15 20:46 UTC
### Reproduction steps

1. Run tests in an existing project using auto-run mode
2. Define a test that calls a non-existent function
3. Implement the function in another file

### What should happen

All tests should pass again.

### What actually happens

The tests fail with `java.lang.Exception: No namespace: some.random.name.space` and an actual namespace. Going into the file for that namespace and saving the file will make this failure go away, but the test will fail with another namespace error. This usually repeats about 4 or 5 times for me before it goes to green.

**EDIT**

I can reproduce this more simply:

1. Run test suite in auto-run mode
2. Change anything in any non-test file and save it

**Comment by slagyr** [comment] 2015-03-09 19:26
I'm also unable to reproduce.  And you're latest "Edit" is very suspicious.   Editing and saving any file, including non-test files, is something I am ALWAYS doing and I do not see there error you describe.

Considerations:
- Is your dev environment creating lots of extra files?  Temp files?
- Is there something unique about your file system such that the test process doesn't see changes right away?

Closing for now.

**Closed by slagyr** 2015-03-09 19:26 UTC
Labels: bug

**Comment by sdegutis** [comment] 2015-03-25 21:30
@slagyr Good points. To answer your questions:

1. My IDE isn't creating any extra files when I save.
2. It's a regular Mac OS X file system (HFS+ Journaled, case sensitive) in Yosemite on a Mac Pro, so I guess it's a pretty average file system.

Either way, someone else seems to be having a similar problem in #127. We should merge these two issues into that one.
